### ISSUE TITLE
Hyper link CTA with secondary style

### ISSUE THREAD

**Issue by braven112** [AlaskaAirlines/OrionStatelessComponents__ods-hyperlink#5]
# Issue report

Making hyperlinks look like buttons is literally the best thing I've ever seen.  Great job!  Now it would be great if we could also have the secondary style with this now option.  Because not every link is the most important thing ever.

## Expected Behavior
Expected to see a prop for CTA type

## Current Behavior
Everything is primary

## Possible Solution
Make an option like there is for Button's

## Context
We are trying to recreate our homepage with with the upgraded Orion styles

## Your Environment
version
1.0.9

**Comment by znewton** [comment]
This would also be helpful on [the route map](https://www.alaskaair.com/route-map) where we use secondary CTA links in the popovers!

**Comment by znewton** [comment]
@blackfalcon is this actively being worked on? If not, I'll need to take this on if we want to use `ods-hyperlink` in this way vs wrapping `ods-button` in `ods-hyperlink`

**Comment by blackfalcon** [comment]
This issue is being developed as part of the https://github.com/AlaskaAirlines/OrionStatelessComponents__ods-button/pull/40 pull request.

**Comment by blackfalcon** [comment]
This issue was addressed with PR #10
